//! Diagnostics: a temporary "usage log" that is deleted on success, plus an
//! issue-ready error report written when a run fails (or panics).
//!
//! On success the temp log is removed. On failure we keep it and write a
//! self-contained `report-<ts>.md` next to it containing the orbit version,
//! the resolved/raw `config.orbit`, the captured error, and a concise tail of
//! the usage log (no full agent conversation). The user is pointed at the
//! report file and a pre-filled GitHub issue URL.

use crate::cli::ORBIT_VERSION;
use crate::config;
use std::path::{Path, PathBuf};

pub const REPO_URL: &str = "https://github.com/claudin-io/orbit";

/// Directory holding orbit's temp artifacts: `$TMPDIR/orbit`.
fn temp_dir() -> PathBuf {
    std::env::temp_dir().join("orbit")
}

/// Unique path for this run's usage log: `$TMPDIR/orbit/orbit-run-<ts>-<pid>.log`.
pub fn temp_log_path() -> PathBuf {
    let ts = chrono::Utc::now().format("%Y%m%d-%H%M%S");
    temp_dir().join(format!("orbit-run-{}-{}.log", ts, std::process::id()))
}

/// Last `n` lines of a file, best-effort (empty string if unreadable).
fn tail(path: &Path, n: usize) -> String {
    match std::fs::read_to_string(path) {
        Ok(contents) => {
            let lines: Vec<&str> = contents.lines().collect();
            let start = lines.len().saturating_sub(n);
            lines[start..].join("\n")
        }
        Err(_) => String::new(),
    }
}

fn read_or_missing(path: &Path) -> String {
    match std::fs::read_to_string(path) {
        Ok(c) if !c.trim().is_empty() => c,
        Ok(_) => "(empty)".to_string(),
        Err(_) => "(not found)".to_string(),
    }
}

/// Minimal percent-encoding for use in a URL query value. No extra deps.
fn percent_encode(s: &str) -> String {
    let mut out = String::with_capacity(s.len() * 3);
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(b as char)
            }
            _ => out.push_str(&format!("%{:02X}", b)),
        }
    }
    out
}

/// Build a pre-filled "new issue" URL with the version and error in the title.
pub fn issue_url(error_display: &str) -> String {
    let first_line = error_display.lines().next().unwrap_or(error_display);
    let title = format!("[bug] {} — {}", ORBIT_VERSION, first_line);
    let body =
        "Describe what you ran. Paste the contents of the report file generated by orbit below:\n\n";
    format!(
        "{}/issues/new?title={}&body={}",
        REPO_URL,
        percent_encode(&title),
        percent_encode(body)
    )
}

/// Write a self-contained markdown error report and return its path.
pub fn write_report(
    log_path: &Path,
    target: &Path,
    explicit_config: Option<&str>,
    error_display: &str,
) -> std::io::Result<PathBuf> {
    let dir = temp_dir();
    std::fs::create_dir_all(&dir)?;
    let ts = chrono::Utc::now().format("%Y%m%d-%H%M%S");
    let report_path = dir.join(format!("report-{}-{}.md", ts, std::process::id()));

    let cfg = config::load(explicit_config, target);
    let resolved = format!(
        "harness = {}\nstep plan = {}\nstep code = {}\nstep eval = {}\nmax_attempts = {}\ntimeout = {}\nacp_retry_max_attempts = {}\nacp_retry_base_delay_ms = {}",
        cfg.harness.to_command_line(),
        cfg.steps.plan.as_ref().map(|h| h.to_command_line()).unwrap_or_else(|| "(default)".into()),
        cfg.steps.code.as_ref().map(|h| h.to_command_line()).unwrap_or_else(|| "(default)".into()),
        cfg.steps.evaluation.as_ref().map(|h| h.to_command_line()).unwrap_or_else(|| "(default)".into()),
        cfg.r#loop.max_attempts,
        cfg.r#loop.prompt_timeout_secs,
        cfg.r#loop.acp_retry_max_attempts,
        cfg.r#loop.acp_retry_base_delay_ms,
    );

    let global_cfg = config::home_config_path()
        .map(|p| read_or_missing(&p))
        .unwrap_or_else(|| "(HOME not set)".to_string());
    let project_cfg = read_or_missing(&config::project_config_path(target));

    let command: String = std::env::args().collect::<Vec<_>>().join(" ");
    let log_tail = tail(log_path, 80);

    let report = format!(
        "# Orbit error report\n\n\
- **Version:** {version}\n\
- **Date (UTC):** {date}\n\
- **OS / Arch:** {os} / {arch}\n\
- **Target:** {target}\n\
- **Command:** `{command}`\n\n\
## Captured error\n\n```\n{error}\n```\n\n\
## Config — resolved\n\n```\n{resolved}\n```\n\n\
## Config — `~/.orbit/config.orbit` (global)\n\n```\n{global_cfg}\n```\n\n\
## Config — `<target>/.orbit/config.orbit` (project)\n\n```\n{project_cfg}\n```\n\n\
## Usage log (tail, last 80 lines)\n\nFull log: `{log_path}`\n\n```\n{log_tail}\n```\n\n\
## How to report\n\n\
Open an issue at {repo}/issues and paste the contents of this file.\n",
        version = ORBIT_VERSION,
        date = chrono::Utc::now().to_rfc3339(),
        os = std::env::consts::OS,
        arch = std::env::consts::ARCH,
        target = target.display(),
        command = command,
        error = error_display,
        resolved = resolved,
        global_cfg = global_cfg,
        project_cfg = project_cfg,
        log_path = log_path.display(),
        log_tail = log_tail,
        repo = REPO_URL,
    );

    std::fs::write(&report_path, report)?;
    Ok(report_path)
}

/// Print a stderr notice pointing the user at the report and a pre-filled issue URL.
pub fn print_failure_notice(report_path: &Path, error_display: &str) {
    let url = issue_url(error_display);
    eprintln!();
    eprintln!("✗ Orbit hit an error. A diagnostic report was saved:");
    eprintln!("    {}", report_path.display());
    eprintln!();
    eprintln!("  Open an issue and paste the report:");
    eprintln!("    {}", url);
    eprintln!();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_percent_encode_basics() {
        assert_eq!(percent_encode("a b"), "a%20b");
        assert_eq!(percent_encode("safe-_.~"), "safe-_.~");
        assert_eq!(percent_encode("a/b?c"), "a%2Fb%3Fc");
    }

    #[test]
    fn test_issue_url_contains_repo_and_version() {
        let url = issue_url("Parse error: No JSON found in evaluator output");
        assert!(url.starts_with(REPO_URL));
        assert!(url.contains("issues/new?title="));
        assert!(url.contains(&percent_encode(ORBIT_VERSION)));
    }

    #[test]
    fn test_temp_log_path_under_temp_dir() {
        let p = temp_log_path();
        assert!(p.starts_with(temp_dir()));
        assert!(p.file_name().unwrap().to_str().unwrap().starts_with("orbit-run-"));
    }

    #[test]
    fn test_write_report_includes_error_and_version() {
        let dir = std::env::temp_dir().join(format!("orbit-report-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let log = dir.join("usage.log");
        std::fs::write(&log, "line1\nline2\nERROR boom\n").unwrap();

        let report = write_report(&log, &dir, None, "Parse error: boom").unwrap();
        let contents = std::fs::read_to_string(&report).unwrap();
        assert!(contents.contains("Parse error: boom"));
        assert!(contents.contains(ORBIT_VERSION));
        assert!(contents.contains("Usage log"));
        assert!(contents.contains("ERROR boom"));

        std::fs::remove_dir_all(&dir).ok();
    }
}
